[dependencies]

[package]
  cjc-version = "0.55.3"
  compile-option = "-Woff unused --diagnostic-format=noColor"
  description = "Through macros implementing code delegation."
  link-option = ""
  name = "delegate"
  output-type = "static"
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  [package.package-configuration]
